# Generated by Django 3.2.5 on 2022-01-29 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='published_at',
            field=models.DateField(blank=True),
        ),
    ]
